#!/usr/bin/env python3
"""Tests for scripts/check_commit_message.py.

Builds a throwaway git repository and runs the checker over real commit
ranges, rather than feeding it synthetic subject strings, so the git
invocation is covered along with the pattern.
"""
import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CHECKER_PATH = REPO_ROOT / "scripts" / "check_commit_message.py"

IDENTITY = (
    "-c", "user.name=Test",
    "-c", "user.email=1+test@users.noreply.github.com",
)


def _load_checker():
    """Import the checker by path, since scripts/ is not an importable package."""
    spec = importlib.util.spec_from_file_location("check_commit_message", CHECKER_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


checker = _load_checker()


class MergeCommitTest(unittest.TestCase):
    """A merge subject is generated by git, not written by an author."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.repo = Path(self.tmp.name)
        self._git("init", "-b", "main")
        self._commit("feat: add the first thing", "one.txt")
        self.base = self._head()
        self._git("checkout", "-b", "side")
        self._commit("fix: correct the second thing", "two.txt")
        self._git("checkout", "main")
        self._commit("chore: touch a third thing", "three.txt")

    def _git(self, *args) -> str:
        result = subprocess.run(
            ["git", *IDENTITY, *args],
            cwd=self.repo, capture_output=True, text=True, check=True,
        )
        return result.stdout.strip()

    def _commit(self, subject: str, filename: str):
        (self.repo / filename).write_text(filename, encoding="utf-8")
        self._git("add", filename)
        self._git("commit", "-m", subject)

    def _head(self) -> str:
        return self._git("rev-parse", "HEAD")

    def _violations(self, base: str) -> list:
        cwd = Path.cwd()
        import os
        os.chdir(self.repo)
        self.addCleanup(os.chdir, cwd)
        return checker.find_violations(checker.load_commits(base, "HEAD"))

    def test_default_merge_subject_is_not_reported(self):
        """`git merge` writes 'Merge branch ...', which no author chose."""
        self._git("merge", "--no-ff", "side")
        subject = self._git("log", "-1", "--format=%s")
        self.assertTrue(subject.startswith("Merge branch"), subject)
        self.assertEqual(self._violations(self.base), [])

    def test_a_real_violation_is_still_reported(self):
        self._commit("Added a thing without a type prefix", "four.txt")
        violations = self._violations(self.base)
        self.assertEqual(len(violations), 1)
        self.assertIn("must start with", violations[0])

    def test_a_violation_reports_without_blocking(self):
        """The check is advisory: it names the problem and exits 0."""
        self._commit("Added a thing without a type prefix", "five.txt")
        result = subprocess.run(
            [sys.executable, str(CHECKER_PATH), "--base", self.base, "--head", "HEAD"],
            cwd=self.repo, capture_output=True, text=True, check=False,
        )
        self.assertEqual(result.returncode, 0)
        self.assertIn("must start with", result.stdout)

    def test_conforming_commits_stay_clean(self):
        self.assertEqual(self._violations(self.base), [])

    def test_ci_commit_type_is_allowed(self):
        self._commit("ci: validate workflow pins", "six.txt")
        self.assertEqual(self._violations(self.base), [])


if __name__ == "__main__":
    unittest.main()
